server:
  port: 9001

spring:
  application:
    name: config-client
  config:
    import: optional:configserver:http://localhost:8888

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: ['refresh', 'info']

logging:
  level:
    com.safecornerscoffee.demo: debug